export default {
  appTitle: 'OUR APP',
  rescanButtonText: 'Tap to Scan Again',
  navBarItemHome: 'Home',
  login: 'LOGIN',
  backButtonText: 'BACK',
  confirmButtonText: 'CONFIRM',
  clearButtonText: 'CLEAR',
  searchButtonText: 'SEARCH',
  newSearchButtonText: 'NEW SEARCH',
  historyButtonText: 'HISTORY',
  editButtonText: 'EDIT',
  productDetailsNameText: 'Name:',
  productDetailsAmountText: 'Amount:',
  productDetailsDescriptionText: 'Description:',
  productDetailsRemarksText: 'Remarks:',
  productDetailsRetailPriceText: 'Retail Price:',
  productDetailsWholesalePriceText: 'Wholesale Price:',
  productDetailsStatusText: 'Status:',
  productDetailsDateLastUpdatedText: 'Date Last Updated:',
  itemNotExistTitleText: 'Item Not Exists',
  itemNotExistContentText: 'Please try some other barcode or contact admin...',
  alertOkayButtonText: 'Okay'
};
